// 由 tools/build.js 產生：版本 = 所有檔案內容的雜湊，任何檔案改動都會換新快取
const CACHE = 'kidlearn-9298ce5531';
const FILES = ["./","css/app.css","css/puzzles.css","css/star.css","css/theme.css","icons/icon-180.png","icons/icon-192.png","icons/icon-512.png","icons/icon-maskable-512.png","index.html","js/books.js","js/content-books.js","js/content-en.js","js/content-ma.js","js/content-plus.js","js/content-star.js","js/content-zh.js","js/content-zh2.js","js/core.js","js/data-en.js","js/data-zh-chars.js","js/data-zhuyin.js","js/games-en.js","js/games-ma.js","js/games-more.js","js/games-plus.js","js/games-star.js","js/games-zh.js","js/garage.js","js/help.js","js/lessons.js","js/puzzles.js","js/shell.js","manifest.webmanifest","vendor/bpmf/F1.wav","vendor/bpmf/F10.wav","vendor/bpmf/F11.wav","vendor/bpmf/F12.wav","vendor/bpmf/F13.wav","vendor/bpmf/F14.wav","vendor/bpmf/F15.wav","vendor/bpmf/F16.wav","vendor/bpmf/F17.wav","vendor/bpmf/F18.wav","vendor/bpmf/F19.wav","vendor/bpmf/F2.wav","vendor/bpmf/F20.wav","vendor/bpmf/F21.wav","vendor/bpmf/F22.wav","vendor/bpmf/F23.wav","vendor/bpmf/F24.wav","vendor/bpmf/F25.wav","vendor/bpmf/F26.wav","vendor/bpmf/F27.wav","vendor/bpmf/F28.wav","vendor/bpmf/F29.wav","vendor/bpmf/F3.wav","vendor/bpmf/F30.wav","vendor/bpmf/F31.wav","vendor/bpmf/F32.wav","vendor/bpmf/F33.wav","vendor/bpmf/F34.wav","vendor/bpmf/F35.wav","vendor/bpmf/F36.wav","vendor/bpmf/F37.wav","vendor/bpmf/F4.wav","vendor/bpmf/F5.wav","vendor/bpmf/F6.wav","vendor/bpmf/F7.wav","vendor/bpmf/F8.wav","vendor/bpmf/F9.wav","vendor/bpmf/LICENSE_MOE.txt","vendor/fonts/andika.LICENSE","vendor/fonts/andika.woff2","vendor/fonts/kai.woff2","vendor/fonts/wenkai.LICENSE","vendor/hanzi-data.js","vendor/hanzi-writer.LICENSE","vendor/hanzi-writer.min.js"];
// cache: 'reload'：安裝新版本時一律向伺服器拿最新檔，不用瀏覽器 HTTP 快取裡的舊檔
self.addEventListener('install', e => e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES.map(f => new Request(f, { cache: 'reload' })))).then(() => self.skipWaiting())));
self.addEventListener('activate', e => e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())));
self.addEventListener('message', e => { if (e.data === 'SKIP_WAITING') self.skipWaiting(); });
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(r => r || fetch(e.request)));
});
